### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.models'

### ISSUE THREAD

**Issue by AmmonZ** [ispc-lab/PointINet#1]
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    from models.models import PointINet
  File "/home/PointINet/models/models.py", line 6, in <module>
    from .layers import SetConv, FlowEmbedding, SetUpConv, FeaturePropagation, PointsFusion
  File "/home/PointINet/models/layers.py", line 9, in <module>
    from kaolin.models.PointNet2 import furthest_point_sampling
ModuleNotFoundError: No module named 'kaolin.models'

**Comment by FanLu97** [comment]
@AmmonZ Thank you for your interest in our work! If you use the latest kaolin library (v0.9), the API has been significantly changed from the version we used (v0.1). Maybe you can change to the previous version of Kaolin and we will try to remove the dependence on kaolin.
