### ISSUE TITLE
About CD_loss

### ISSUE THREAD

**Issue by Panghu-coder** [ispc-lab/PointINet#3]
The CD loss in your paper removes the square? Would you like to explain for it?

**Comment by FanLu97** [comment]
@Panghu-coder 
Hello, If you mean the CD loss in Eq.4 in our paper, we think it's a standard chamfer distance, where the ||*||_2 represents L2-norm, which includes the sqrt. We use pytorch3d to implement the chamfer distance in our code.

**Comment by Panghu-coder** [comment]
> @Panghu-coder
> Hello, If you mean the CD loss in Eq.4 in our paper, we think it's a standard chamfer distance, where the ||*||_2 represents L2-norm, which includes the sqrt. We use pytorch3d to implement the chamfer distance in our code.

Hello, sorry to interupt you again, but according to your reference, a standard chamfer distance includes the square of ||*||_2, not the ||*||_2.

**Comment by FanLu97** [comment]
@Panghu-coder 
Hello, thank you for pointing this out. In fact, we use the default implementation in pytorch3d library for chamfer distance, which should be a standard chamfer distance, including the *squared* operation.
